# Bevy Game Asset Generation Configuration
# This configuration generates complete asset packs for Bevy game development

# High-level game description - AI will analyze and create optimized asset workflow
task = """
Create complete asset pack for a fantasy 2D RPG game using Bevy engine.
Need pixel art sprites for hero characters, enemies, and NPCs.
Generate seamless tilemap for dungeon environments with walls, floors, doors, and decorative elements.
Create UI elements with medieval fantasy theming including buttons, panels, health bars, and inventory slots.
Add particle effects for magic spells, fire, and combat effects.
Generate PBR materials for 3D dungeon props like chests, torches, and stone pillars.
All assets should be Bevy-compatible with proper metadata and integration code.
"""

# Specific Bevy asset workflows
[[workflows]]
name = "Fantasy RPG Bevy Assets"
type = "game_assets"
description = "Complete Bevy-compatible asset generation for fantasy RPG"
output_format = "png"
optimization = "quality"

# Bevy-specific settings
[workflows.bevy_settings]
target_engine = "bevy_0_12"
asset_structure = "bevy_compatible"
generate_metadata = true
include_integration_code = true

# 2D Sprites for Bevy ECS
[[workflows.bevy_assets]]
type = "sprite_2d"
name = "hero_warrior"
description = "Fantasy warrior character sprite with sword and armor"
size = "64x64"
style = "pixel art"
transparent = true
animation_frames = 4
bevy_components = ["Sprite", "Transform", "Player", "Health", "Combat"]

[[workflows.bevy_assets]]
type = "sprite_2d" 
name = "goblin_enemy"
description = "Green goblin enemy with simple weapons"
size = "48x48"
style = "pixel art"
transparent = true
animation_frames = 2
bevy_components = ["Sprite", "Transform", "Enemy", "Health", "AI"]

# Tilemap Generation
[[workflows.bevy_assets]]
type = "tilemap"
name = "dungeon_tileset"
description = "Medieval dungeon tilemap with stone walls and floors"
tile_size = [32, 32]
tile_count = 16
seamless = true
bevy_components = ["TilemapBundle", "TileStorage"]

# UI Theme
[[workflows.bevy_assets]]
type = "ui_theme"
name = "fantasy_ui"
description = "Medieval fantasy UI theme with stone and wood elements"
elements = ["button_normal", "button_hover", "panel", "health_bar", "inventory_slot"]
style = "fantasy medieval"
transparent = true
bevy_components = ["NodeBundle", "ButtonBundle", "ImageBundle"]

# Particle Systems
[[workflows.bevy_assets]]
type = "particles"
name = "magic_effects"
description = "Magical particle effects for spells and enchantments"
effect_types = ["magic", "fire", "explosion"]
particle_count = 6
size = "128x128"
transparent = true

# PBR Materials for 3D assets
[[workflows.bevy_assets]]
type = "pbr_material"
name = "stone_wall"
description = "Medieval stone wall texture with moss and weathering"
size = "1024x1024"
maps = ["albedo", "normal", "roughness"]
material_type = "standard"
seamless = true

# Verification for game assets
[workflows.verification]
mode = "basic"
style_consistency = true
quality_threshold = 0.8
max_regenerations = 2
required_objects = ["game asset", "pixel art", "fantasy"]
forbidden_objects = ["photograph", "realistic portrait", "modern"]

# Batch processing optimized for game development
[workflows.batch_settings]
concurrent_limit = 4
retry_failed = true
group_by_type = true
generate_atlas = true
optimize_for_engine = "bevy"