[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "fastmcp>=2.12.2",
    "openai>=1.106.1",
    "pillow>=11.3.0",
    "pydantic>=2.11.7",
    "tiktoken>=0.11.0",
]
