[project]
name = "ai-game-dev-workspace"
version = "1.0.0"
description = "Revolutionary AI-powered game development ecosystem"
authors = [
    {name = "AI Game Dev Team"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    # Core AI and Language Models
    "openai>=1.51.0",
    "langchain>=0.3.9",
    "langchain-core>=0.3.21",
    "langchain-community>=0.3.8",
    "langchain-openai>=0.2.11",
    "langgraph>=0.2.45",
    "langgraph-checkpoint>=2.0.4",
    
    # MCP Server Framework
    "fastmcp>=0.10.0",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "websockets>=12.0",
    "python-multipart>=0.0.6",
    
    # Audio and Music
    "music21>=8.0.0",
    "freesound-python>=0.7.0",
    
    # Machine Learning and AI
    "torch>=2.0.0",
    "transformers>=4.36.0",
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    
    # Web and Assets
    "requests>=2.31.0",
    "aiohttp>=3.9.0",
    "internetarchive>=3.5.0",
    "pillow>=10.0.0",
    
    # Core Libraries
    "pydantic>=2.8.0",
    "pydantic-settings>=2.4.0",
    "aiofiles>=23.2.1",
    "jinja2>=3.1.0",
    "pyyaml>=6.0",
    "rich>=13.7.0",
    "tiktoken>=0.7.0",
    "tomli>=2.0.0",
    "xdg-base-dirs>=6.0.0",
    
    # Web Portal
    "mesop>=0.12.0",
    
    # Development and Testing
    "pytest>=8.4.2",
    "pytest-asyncio>=1.1.0",
]

[tool.uv]
dev-dependencies = [
    "black>=23.0.0",
    "ruff>=0.6.0",
    "mypy>=1.11.0",
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=2.0.0",
]

[tool.uv.workspace]
members = [
    "packages/ai-game-dev-core",
    "packages/ai-game-assets",
    "packages/web-portal"
]

[tool.uv.sources]
ai-game-dev-core = { workspace = true }
ai-game-assets = { workspace = true }
web-portal = { workspace = true }

[build-system]
requires = ["uv>=0.5.0"]
build-backend = "uv"

[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true