[project]
name = "ai-game-assets"
version = "1.0.0"
description = "Standalone multimedia asset generation library with OpenAI, Google Fonts, and CC0 resources"
authors = [
    {name = "AI Game Dev Team"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    # Core AI and Generation
    "openai>=1.51.0",
    "langchain-core>=0.3.21",
    
    # Audio and Music
    "music21>=8.0.0",
    "freesound-python>=0.7.0",
    
    # Machine Learning and AI
    "torch>=2.0.0",
    "transformers>=4.36.0",
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    
    # Web and Assets
    "requests>=2.31.0",
    "aiohttp>=3.9.0",
    "internetarchive>=3.5.0",
    "pillow>=10.0.0",
    
    # Core Libraries
    "pydantic>=2.8.0",
    "pydantic-settings>=2.4.0",
    "aiofiles>=23.2.1",
    "rich>=13.7.0",
    "tiktoken>=0.7.0",
    "xdg-base-dirs>=6.0.0",
]

[build-system]
requires = ["uv>=0.5.0"]
build-backend = "uv"