[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "arcade-ai-game-dev"
version = "1.0.0"
description = "Native Arcade game generation bindings for AI game development"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
authors = [
    {name = "AI Game Dev Team"},
]
keywords = ["arcade", "gamedev", "ai", "procedural", "2d", "3d"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers", 
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "arcade>=3.0.0",
]

[project.optional-dependencies]
physics = ["pymunk>=6.5.0"]
ai = ["numpy>=1.21.0"]
dev = [
    "pytest>=7.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
]

[project.urls]
Homepage = "https://github.com/ai-game-dev/arcade-ai-game-dev"
Repository = "https://github.com/ai-game-dev/arcade-ai-game-dev"
"Bug Tracker" = "https://github.com/ai-game-dev/arcade-ai-game-dev/issues"

[tool.hatch.build.targets.wheel]
packages = ["arcade_game_dev"]