[project]
name = "web-portal"
version = "1.0.0"
description = "Mesop-powered web portal for AI game development"
authors = [
    {name = "AI Game Dev Team"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "ai-game-dev-core",
    "mesop>=0.12.0",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "python-multipart>=0.0.6",
]

[build-system]
requires = ["uv>=0.5.0"]
build-backend = "uv"

[tool.uv.sources]
ai-game-dev-core = { workspace = true }