# Example Game Specification - Educational RPG (Arcade Academy)

[game]
title = "NeoTokyo Code Academy"
description = "An educational RPG where students learn programming concepts through cyberpunk adventures"
genre = "rpg"
engine = "pygame"
art_style = "cyberpunk_pixel"
educational_mode = true

[features]
core = [
    "dialogue_system",
    "quest_tracking",
    "skill_tree",
    "inventory_management",
    "npc_interactions",
    "puzzle_solving",
    "combat_system",
    "save_system"
]

educational = [
    "interactive_code_challenges",
    "teachable_moments",
    "progress_tracking",
    "concept_reinforcement",
    "visual_programming_metaphors"
]

[characters]
player = "Student Hacker"
mentor = "Professor Pixel"
npcs = [
    "Web Weaver",
    "Data Sage", 
    "Code Knight",
    "Bug Hunter",
    "The Compiler"
]

[learning_objectives]
concepts = [
    "variables",
    "conditionals",
    "loops",
    "functions",
    "classes",
    "data_structures",
    "algorithms",
    "debugging"
]

[assets]
sprites = [
    "player_student",
    "professor_pixel",
    "npc_web_weaver",
    "npc_data_sage",
    "npc_code_knight",
    "npc_bug_hunter",
    "enemy_bug",
    "enemy_syntax_error",
    "item_code_fragment",
    "item_debug_tool",
    "tileset_academy",
    "tileset_cyberspace"
]

sounds = [
    "code_compile",
    "bug_squash",
    "level_up",
    "quest_complete",
    "dialogue_beep",
    "error_buzz"
]

music = [
    "academy_theme",
    "cyberspace_ambient",
    "boss_battle_glitch",
    "victory_celebration"
]

[dialogue]
format = "yarnspinner"
branching = true
educational_hints = true

[progression]
xp_per_concept = 100
levels = 20
skill_points_per_level = 3
unlock_sequence = "linear_with_branches"