# Example Game Specification - Classic Platformer

[game]
title = "Pixel Quest Adventures"
description = "A classic 2D platformer with pixel art style, featuring a brave hero collecting gems while avoiding enemies"
genre = "platformer"
engine = "pygame"
art_style = "pixel"

[features]
core = [
    "player_movement",
    "jumping",
    "double_jump",
    "enemy_ai",
    "collectibles",
    "level_progression",
    "score_system"
]

[assets]
sprites = [
    "player_idle",
    "player_run",
    "player_jump",
    "enemy_slime",
    "gem_blue",
    "gem_red",
    "platform_grass",
    "background_forest"
]

sounds = [
    "jump",
    "collect_gem",
    "enemy_defeat",
    "level_complete"
]

music = [
    "main_theme",
    "level_music",
    "victory_fanfare"
]

[gameplay]
player_speed = 300
jump_strength = -500
gravity = 980
enemy_speed = 100
gem_value = 10
lives = 3

[levels]
count = 5
themes = ["forest", "cave", "castle", "sky", "final_boss"]
difficulty_progression = "gradual"