#!/usr/bin/env python3
"""
AI Game Development Package Demo
Demonstrates the core functionality of the AI game development system
"""

import asyncio
from pathlib import Path

def main():
    """Demo the AI game development system."""
    print("🎮 AI Game Development System")
    print("=" * 40)
    
    try:
        from library import AIGameDev
        from models import GameSpec, GameType, ComplexityLevel
        
        # Create a simple game specification
        spec = GameSpec(
            name="Demo Game",
            description="A simple demo game generated by AI",
            game_type=GameType.TWO_DIMENSIONAL,
            features=["player movement", "basic gameplay"],
            complexity=ComplexityLevel.BEGINNER
        )
        
        print(f"✅ Game spec created: {spec.name}")
        print(f"📋 Type: {spec.game_type}")
        print(f"🎯 Complexity: {spec.complexity}")
        print("🚀 AI Game Development system is ready!")
        
    except ImportError as e:
        print(f"⚠️  Import note: {e}")
        print("🔧 This package is part of a workspace - use UV sync for full setup")
    
    print("=" * 40)

if __name__ == "__main__":
    main()