[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ai-game-dev"
version = "1.0.0"
description = "Revolutionary AI-powered game development with LangGraph orchestration"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
authors = [
    {name = "AI Game Dev Team"},
]
keywords = ["ai", "gamedev", "langgraph", "langchain", "procedural"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "langchain>=0.3.9",
    "langchain-core>=0.3.21", 
    "langchain-openai>=0.2.11",
    "langgraph>=0.2.45",
    "pydantic>=2.8.0",
    "aiofiles>=23.2.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
]

[project.urls]
Homepage = "https://github.com/ai-game-dev/ai-game-dev"
Repository = "https://github.com/ai-game-dev/ai-game-dev"
Documentation = "https://ai-game-dev.readthedocs.io"
"Bug Tracker" = "https://github.com/ai-game-dev/ai-game-dev/issues"

[tool.hatch.build.targets.wheel]
packages = ["ai_game_dev"]