# Web Platform Asset Generation Specification
# This defines ALL the assets we need to generate for our own platform
# using our internal batch generation tooling

[platform_info]
name = "AI Game Dev Complete Platform"
description = "Unified asset specification for web platform AND educational experience"
generation_method = "internal_batch_tooling"

# Navigation and Control Assets
[assets.navigation_buttons]
prompts = [
    "Left arrow navigation button, cyberpunk neon cyan glow, rounded square, transparent background, futuristic tech design",
    "Right arrow navigation button, cyberpunk neon cyan glow, rounded square, transparent background, futuristic tech design",
    "Up arrow button, cyberpunk neon blue glow, rounded square, transparent background, tech interface style",
    "Down arrow button, cyberpunk neon blue glow, rounded square, transparent background, tech interface style",
    "Home button icon, cyberpunk neon green glow, house shape, transparent background, futuristic UI design",
    "Menu hamburger button, cyberpunk neon purple glow, three lines, transparent background, tech aesthetic"
]
size = "512x512"
quality = "hd"
category = "ui_controls"

# Audio Interface Components
[assets.audio_controls]
prompts = [
    "Play button icon, cyberpunk neon pink triangle, rounded square background, transparent, high contrast tech design",
    "Pause button icon, cyberpunk neon cyan double bars, rounded square background, transparent, futuristic style",
    "Stop button icon, cyberpunk neon blue square, rounded background, transparent, tech interface design",
    "Skip forward button, cyberpunk neon orange double triangles, transparent background, sci-fi aesthetic",
    "Skip backward button, cyberpunk neon orange double triangles pointing left, transparent background, sci-fi style",
    "Volume up icon, cyberpunk neon green speaker with plus, transparent background, tech design",
    "Volume down icon, cyberpunk neon green speaker with minus, transparent background, tech design",
    "Mute button icon, cyberpunk neon red speaker with X, transparent background, futuristic style"
]
size = "256x256"
quality = "hd"
category = "audio_interface"

# Engine Selection Artwork
[assets.engine_panels]
prompts = [
    "Pygame engine artwork, Python snake with game controller, vibrant orange and blue colors, cyberpunk tech background, 320x240 aspect",
    "Bevy engine artwork, Rust crab with 3D geometric shapes, orange and metallic colors, futuristic tech background, 320x240 aspect",
    "Godot engine artwork, blue robot mascot with game elements, blue and white colors, sci-fi tech background, 320x240 aspect",
    "Unity engine artwork, cube logo with particle effects, black and white colors, tech grid background, 320x240 aspect",
    "Unreal engine artwork, stylized U with epic visual effects, blue and orange colors, tech background, 320x240 aspect"
]
size = "1024x768"
quality = "hd"
category = "engine_showcase"

# UI Framework Components
[assets.frame_elements]
prompts = [
    "Tech frame border, cyberpunk circuit pattern, neon cyan lines, transparent center, corner lightning effects",
    "Glass panel overlay, frosted glass effect, subtle cyan tint, transparent edges, soft glow border",
    "Circuit pattern texture, intricate electronic pathways, neon blue lines, seamless tiling, dark background",
    "Energy field texture, flowing electric particles, animated-style, cyan and blue colors, seamless pattern",
    "Holographic grid texture, futuristic grid lines, neon green glow, transparent background, tech aesthetic",
    "Metal plate texture, brushed steel surface, subtle blue lighting, industrial tech look, seamless tiling"
]
size = "512x512"
quality = "hd"
category = "ui_frames"

# Status and Feedback Icons
[assets.status_indicators]
prompts = [
    "Success checkmark icon, cyberpunk neon green check, rounded background, transparent, glowing effect",
    "Error X icon, cyberpunk neon red X, rounded background, transparent, warning glow effect",
    "Warning triangle icon, cyberpunk neon yellow triangle with exclamation, transparent, alert design",
    "Info circle icon, cyberpunk neon blue circle with i, transparent background, information glow",
    "Loading spinner icon, cyberpunk neon cyan rotating ring, transparent background, animated style",
    "Progress bar empty, cyberpunk tech design, dark gray with cyan border, transparent background",
    "Progress bar full, cyberpunk tech design, bright cyan fill with glow, transparent background"
]
size = "128x128"
quality = "hd"
category = "status_feedback"

# Project and File Management Icons
[assets.file_management]
prompts = [
    "Folder icon, cyberpunk neon blue folder, transparent background, tech design with glow",
    "File icon, cyberpunk neon white document, transparent background, tech aesthetic with corner fold",
    "Code file icon, cyberpunk neon green document with brackets, transparent background, programming theme",
    "Image file icon, cyberpunk neon purple document with picture symbol, transparent background, media theme",
    "Download icon, cyberpunk neon cyan arrow pointing down, transparent background, tech design",
    "Upload icon, cyberpunk neon cyan arrow pointing up, transparent background, tech design",
    "Save icon, cyberpunk neon green floppy disk, transparent background, retro-futuristic style",
    "Delete icon, cyberpunk neon red trash can, transparent background, warning glow effect"
]
size = "128x128"
quality = "hd"
category = "file_operations"

# Generation and AI Processing Icons
[assets.ai_generation]
prompts = [
    "AI brain icon, cyberpunk neon pink brain with circuit patterns, transparent background, tech glow",
    "Generate icon, cyberpunk neon cyan magic wand with sparkles, transparent background, creation theme",
    "Processing icon, cyberpunk neon blue gear wheels interlocked, transparent background, working animation style",
    "Robot head icon, cyberpunk neon white robot face, transparent background, AI assistant theme",
    "Lightning bolt icon, cyberpunk neon yellow lightning, transparent background, power and speed theme",
    "Refresh icon, cyberpunk neon green circular arrows, transparent background, renewal theme"
]
size = "128x128"
quality = "hd"
category = "ai_tools"

# Social and Sharing Icons
[assets.social_features]
prompts = [
    "Share icon, cyberpunk neon blue branching arrows, transparent background, distribution theme",
    "Export icon, cyberpunk neon cyan box with arrow out, transparent background, output theme",
    "Collaborate icon, cyberpunk neon purple multiple user silhouettes, transparent background, teamwork theme",
    "Comment icon, cyberpunk neon white speech bubble, transparent background, communication theme",
    "Like icon, cyberpunk neon pink heart, transparent background, appreciation theme",
    "Star rating icon, cyberpunk neon yellow star, transparent background, quality theme"
]
size = "128x128"
quality = "hd"
category = "social_interaction"

# Background and Environment Assets
[assets.backgrounds]
prompts = [
    "Cyberpunk cityscape background, neon lights, dark atmosphere, futuristic skyscrapers, tech aesthetic",
    "Digital matrix background, flowing code characters, green on black, transparent overlay version",
    "Space nebula background, cosmic colors, purple and blue swirls, stars, mystical tech theme",
    "Circuit board background, intricate electronic pathways, neon green traces, dark substrate",
    "Holographic interface background, floating UI elements, cyan and blue colors, transparent layers"
]
size = "1920x1080"
quality = "hd"
category = "environment"

# Logo and Branding Assets
[assets.branding]
prompts = [
    "AI Game Dev logo, futuristic text with game controller elements, cyberpunk neon colors, transparent background",
    "Platform mascot character, friendly AI robot, cyberpunk style, neon accents, game development tools",
    "Loading screen logo, animated style AI Game Dev text, particle effects, tech glow",
    "Favicon icon, simplified AI Game Dev symbol, 32x32 pixel art style, recognizable at small size"
]
size = "512x512"
quality = "hd"
category = "brand_identity"

# Procedural Audio Effect Specifications
[assets.procedural_audio]
prompts = [
    "Waveform visualization for synthesized laser blaster sound effect, sharp attack, neon green frequency display",
    "Audio spectrum analyzer for procedural explosion sound, wide frequency spread, orange and red visualization",
    "Sound wave pattern for cyberpunk ambient drone, low frequency, blue and cyan waveform display",
    "Frequency graph for procedural footstep generator, percussive spikes, white and gray visualization",
    "Audio synthesis interface for spaceship engine sound, continuous wave, purple and pink frequency bands",
    "Procedural music generator visualization, harmonic overtones, rainbow spectrum frequency display",
    "Sound effect mixer interface, multiple channel visualization, neon blue and cyan waveforms",
    "Audio filter visualization for sci-fi interface sounds, filtered frequencies, green and yellow display"
]
size = "512x256"
quality = "hd"
category = "audio_generation"

# Audio Effect Library Specifications  
[assets.sound_library]
prompts = [
    "Sound effect library icon collection, various game audio symbols, neon cyan outlines, transparent background",
    "Procedural audio generator interface, synthesis controls and parameters, cyberpunk tech design",
    "Audio waveform editor visualization, multi-track display, futuristic interface with neon accents",
    "Sound mixing console interface, professional audio controls, dark theme with glowing elements",
    "Frequency analyzer display for game audio, real-time spectrum, cyberpunk visualization style",
    "Audio effect chain visualization, connected processing nodes, tech circuit pattern design"
]
size = "512x512"
quality = "hd"
category = "audio_tools"

# Unified Generation Configuration
[batch_config]
total_visual_assets = 65
total_audio_assets = 19
concurrent_limit = 3
batch_size = 5
visual_output_directory = "src/ai_game_dev/server/static/assets/generated/"
audio_output_directory = "src/ai_game_dev/server/static/assets/audio/"
visual_naming_convention = "{category}_{index}_{hash}.png"
audio_naming_convention = "{effect_name}.{format}"
fallback_quality = "standard"
retry_failed = true
max_retries = 2

# UI Sound Effects
[audio.ui_sounds]
effects = [
    "button_click_futuristic",
    "hover_beep_cyberpunk", 
    "notification_chime_tech",
    "error_buzz_warning",
    "success_ding_pleasant",
    "menu_open_whoosh",
    "menu_close_whoosh_reverse",
    "typing_mechanical_keyboard"
]
duration_ms = [200, 300, 500, 400, 350, 600, 600, 100]
format = "wav"
category = "interface"

# Game Sound Effects
[audio.game_effects]
effects = [
    "laser_blaster_zap",
    "explosion_medium_boom", 
    "footstep_metal_clank",
    "pickup_item_bling",
    "powerup_energy_surge",
    "engine_spaceship_hum",
    "sword_slash_whoosh",
    "magic_spell_cast_sparkle"
]
duration_ms = [800, 1500, 300, 400, 1000, 2000, 600, 1200]
format = "wav"
category = "gameplay"

# Ambient Audio
[audio.ambient]
effects = [
    "cyberpunk_city_atmosphere",
    "space_station_hum", 
    "tech_lab_computer_buzz"
]
duration_ms = [10000, 8000, 9000]
format = "wav"
category = "atmosphere"
loop = true

# Audio Generation Configuration
[audio_generation]
sample_rate = 44100
bit_depth = 16
output_directory = "src/ai_game_dev/server/static/assets/audio/"
supported_formats = ["wav", "mp3", "ogg"]
synthesis_methods = ["additive", "subtractive", "fm", "granular", "physical_modeling"]
effect_types = ["reverb", "delay", "distortion", "filter", "chorus", "phaser"]

# Educational Experience Assets
[assets.professor_pixel]
prompts = [
    "Professor Pixel character portrait, cyberpunk mentor with neon hair and AR glasses, friendly smile, tech background",
    "Professor Pixel full body sprite, cyberpunk professor with lab coat and holographic tablet, 64x64 pixel art style",
    "Professor Pixel avatar icon, circular portrait with neon cyan hair and AR glasses, transparent background",
    "Professor Pixel teaching pose, pointing gesture with holographic code display, cyberpunk classroom setting"
]
size = "512x512"
quality = "hd"
category = "educational_characters"

# NeoTokyo RPG Character Classes
[assets.rpg_characters]
prompts = [
    "Code Knight character sprite, cybernetic warrior with plasma sword, red and blue armor, 64x64 pixel art",
    "Data Sage character sprite, mystical hacker with holographic robes, purple and cyan colors, 64x64 pixel art",
    "Bug Hunter character sprite, agile cyber-assassin with stealth cloak, green and black colors, 64x64 pixel art",
    "Web Weaver character sprite, digital architect with quantum tablet, orange and white colors, 64x64 pixel art",
    "System Admin character sprite, tech support hero with diagnostic tools, yellow and gray colors, 64x64 pixel art"
]
size = "64x64"
quality = "hd"
category = "rpg_player_classes"

# Educational Game Environments
[assets.neotokyo_environments]
prompts = [
    "NeoTokyo Code Academy exterior, cyberpunk school building with neon signs, night scene, 16-bit pixel art",
    "Underground programming lab interior, hidden rebel coding classroom, holographic displays, pixel art tileset",
    "Algorithm Tower lobby, corporate empire data center, sleek tech architecture, cyberpunk pixel art",
    "Digital marketplace, cyberpunk bazaar with code vendors, neon lights and tech stalls, pixel art scene",
    "Virus-infected sector, corrupted digital environment with glitching effects, dangerous cyberpunk zone"
]
size = "512x512"
quality = "hd"
category = "educational_environments"

# Educational UI Elements
[assets.educational_ui]
prompts = [
    "Code learning progress bar, cyberpunk style with skill points, neon green fill, transparent background",
    "XP gain notification popup, cyberpunk design with congratulations text, glowing effect",
    "Skill tree interface background, tech circuit pattern with connection nodes, dark cyberpunk theme",
    "Lesson complete badge, cyberpunk achievement icon with checkmark, neon cyan glow",
    "Coding challenge icon, cyberpunk puzzle symbol with binary code, tech aesthetic",
    "Tutorial arrow pointer, cyberpunk neon cyan arrow with glow effect, transparent background"
]
size = "256x256"
quality = "hd"
category = "educational_interface"

# Batch Config Update
[batch_config]
total_assets = 89
output_directory = "src/ai_game_dev/server/static/assets/generated/"
concurrent_requests = 3
retry_attempts = 2