[package]
name = "bevy-ai-game-dev"
version = "1.0.0"
edition = "2021"
authors = ["AI Game Dev Team <dev@ai-game-dev.io>"]
description = "Native Rust bindings for Bevy game engine integration with AI Game Development ecosystem"
documentation = "https://docs.rs/bevy-ai-game-dev"
homepage = "https://github.com/jbcom/ai_game_dev"
repository = "https://github.com/jbcom/ai_game_dev"
license = "MIT"
keywords = ["bevy", "gamedev", "ai", "procedural", "ecs"]
categories = ["game-development", "game-engines"]
readme = "README.md"
rust-version = "1.70"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
]

[dependencies]
bevy = { version = "0.14", default-features = false, features = ["default"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = ["2d", "3d"]
2d = []
3d = []
physics = []
audio = []
ai = []

# Enable more pedantic linting
[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "warn"
nursery = "warn"
unwrap_used = "deny"

[lib]
name = "bevy_ai_game_dev"
crate-type = ["cdylib", "rlib"]

# Documentation settings
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# Benchmark configuration
[[bench]]
name = "generation_benchmarks"
harness = false
required-features = ["2d", "3d"]