[package]
name = "bevy-ai-game-dev"
version = "0.1.0"
edition = "2021"
description = "Native Rust Bevy game development bindings for AI-powered game generation"
license = "MIT"
repository = "https://github.com/ai-game-dev/bevy-ai-game-dev"
homepage = "https://github.com/ai-game-dev/bevy-ai-game-dev"
documentation = "https://docs.rs/bevy-ai-game-dev"
keywords = ["bevy", "gamedev", "ai", "procedural", "ecs"]
categories = ["game-development", "game-engines"]
authors = ["AI Game Dev Team"]
readme = "README.md"
rust-version = "1.70"

[dependencies]
bevy = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

[dev-dependencies]
tokio-test = "0.4"

[lib]
name = "bevy_ai_game_dev"
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]